/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is running and can serve requests.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: dependencies (DB + Redis) are reachable.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Events
         * @description Events API endpoint: URL handshake + normalized event intake.
         */
        post: operations["slack_events_slack_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Commands
         * @description Slash command endpoint (``/flare``). ACKs ephemerally; no work yet.
         */
        post: operations["slack_commands_slack_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Interactions
         * @description Interactivity endpoint (buttons/modals/menus). ACKs; no work yet.
         */
        post: operations["slack_interactions_slack_interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slack Oauth Callback
         * @description Install flow: exchange ``code`` and persist a ``workspaces`` row.
         */
        get: operations["slack_oauth_callback_slack_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description List incidents, newest first.
         */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Incident Detail
         * @description Overview: the incident, its current summary, and per-entity counts.
         */
        get: operations["get_incident_detail_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description The current (highest-version) summary for a scope.
         */
        get: operations["get_summary_api_v1_incidents__incident_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facts */
        get: operations["list_facts_api_v1_incidents__incident_id__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evidence
         * @description Evidence for an incident, filterable by source system and status.
         */
        get: operations["list_evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hypotheses
         * @description Hypotheses with their supporting/contradicting evidence resolved.
         *
         *     Evidence is attached via the polymorphic ``evidence_links`` table, so this
         *     resolves links in two queries rather than one per hypothesis.
         */
        get: operations["list_hypotheses_api_v1_incidents__incident_id__hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_v1_incidents__incident_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_v1_incidents__incident_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Action Items */
        get: operations["list_action_items_api_v1_incidents__incident_id__action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Timeline
         * @description Timeline ordered by when things happened, not when we recorded them.
         */
        get: operations["list_timeline_api_v1_incidents__incident_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/mitigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mitigations */
        get: operations["list_mitigations_api_v1_incidents__incident_id__mitigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/comms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comms */
        get: operations["list_comms_api_v1_incidents__incident_id__comms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/postmortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Postmortem
         * @description The latest postmortem draft (drafts are versioned like summaries).
         */
        get: operations["get_postmortem_api_v1_incidents__incident_id__postmortem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Investigation runs, most recent first.
         */
        get: operations["list_runs_api_v1_incidents__incident_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description A run with its agent traces and each trace's tool calls.
         *
         *     The run is matched on ``incident_id`` too, so a run id from another
         *     incident 404s rather than leaking across incidents.
         */
        get: operations["get_run_detail_api_v1_incidents__incident_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Revisions
         * @description The memory journal for an incident, oldest first (it reads as history).
         */
        get: operations["list_revisions_api_v1_incidents__incident_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Incident
         * @description Subscribe to an incident's live event feed.
         */
        get: operations["stream_incident_api_v1_incidents__incident_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemRead */
        ActionItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Description */
            description?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** AgentTraceRead */
        AgentTraceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Agent Name */
            agent_name: string;
            /** Seq */
            seq?: number | null;
            /** Status */
            status?: string | null;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Reasoning Summary */
            reasoning_summary?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Tokens */
            tokens?: {
                [key: string]: unknown;
            } | null;
            /** Model Name */
            model_name?: string | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRead"][];
        };
        /** CommsDraftRead */
        CommsDraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Audience */
            audience?: string | null;
            /** Body */
            body?: string | null;
            /** Version */
            version?: number | null;
        };
        /** DecisionRead */
        DecisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Rationale */
            rationale?: string | null;
        };
        /** EvidenceRead */
        EvidenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** System */
            system?: string | null;
            /** Query */
            query?: string | null;
            /** Result Ref */
            result_ref?: {
                [key: string]: unknown;
            } | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Staleness At */
            staleness_at?: string | null;
        };
        /** FactRead */
        FactRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HypothesisRead */
        HypothesisRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
            /** Rank */
            rank?: number | null;
            /** Likelihood */
            likelihood?: number | null;
            /** Supporting Evidence */
            supporting_evidence?: components["schemas"]["EvidenceRead"][];
            /** Contradicting Evidence */
            contradicting_evidence?: components["schemas"]["EvidenceRead"][];
        };
        /**
         * IncidentDetail
         * @description Overview payload: the incident, its current summary, and counts.
         */
        IncidentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Slack Channel Id */
            slack_channel_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity?: string | null;
            /** Mode */
            mode: string;
            /** Started At */
            started_at?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Mitigated At */
            mitigated_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            summary?: components["schemas"]["SummaryRead"] | null;
            counts: components["schemas"]["IncidentSummaryCounts"];
        };
        /** IncidentRead */
        IncidentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Slack Channel Id */
            slack_channel_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity?: string | null;
            /** Mode */
            mode: string;
            /** Started At */
            started_at?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Mitigated At */
            mitigated_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IncidentSummaryCounts
         * @description Per-entity counts shown on the overview header.
         */
        IncidentSummaryCounts: {
            /**
             * Facts
             * @default 0
             */
            facts: number;
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /**
             * Hypotheses
             * @default 0
             */
            hypotheses: number;
            /**
             * Open Questions
             * @default 0
             */
            open_questions: number;
            /**
             * Decisions
             * @default 0
             */
            decisions: number;
            /**
             * Action Items
             * @default 0
             */
            action_items: number;
            /**
             * Timeline Entries
             * @default 0
             */
            timeline_entries: number;
            /**
             * Mitigation Options
             * @default 0
             */
            mitigation_options: number;
        };
        /** MitigationOptionRead */
        MitigationOptionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Risk */
            risk?: string | null;
            /** Reversibility */
            reversibility?: string | null;
            /** Expected Benefit */
            expected_benefit?: string | null;
            /** Approval Required */
            approval_required?: boolean | null;
        };
        /** OpenQuestionRead */
        OpenQuestionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Question */
            question?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Answer */
            answer?: string | null;
        };
        /** PostmortemDraftRead */
        PostmortemDraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Sections */
            sections?: {
                [key: string]: unknown;
            } | null;
            /** Follow Ups */
            follow_ups?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Version */
            version: number;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RevisionRead */
        RevisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Op */
            op: string;
            /** Before */
            before?: {
                [key: string]: unknown;
            } | null;
            /** After */
            after?: {
                [key: string]: unknown;
            } | null;
            /** Diff */
            diff?: {
                [key: string]: unknown;
            } | null;
            /** Actor */
            actor?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Reason */
            reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunDetail
         * @description A run plus its agent traces and the tool calls beneath them.
         */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Run Type */
            run_type: string;
            /** Trigger */
            trigger?: {
                [key: string]: unknown;
            } | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Token In */
            token_in?: number | null;
            /** Token Out */
            token_out?: number | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Limitations */
            limitations?: string[] | null;
            /** Summary */
            summary?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Agent Traces */
            agent_traces?: components["schemas"]["AgentTraceRead"][];
        };
        /** RunRead */
        RunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Run Type */
            run_type: string;
            /** Trigger */
            trigger?: {
                [key: string]: unknown;
            } | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Token In */
            token_in?: number | null;
            /** Token Out */
            token_out?: number | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Limitations */
            limitations?: string[] | null;
            /** Summary */
            summary?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SummaryRead */
        SummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Scope */
            scope: string;
            /** Body */
            body?: string | null;
            /** Version */
            version: number;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TimelineEntryRead */
        TimelineEntryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Entry Type */
            entry_type?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ToolCallRead */
        ToolCallRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Run Id */
            run_id?: string | null;
            /** Agent Trace Id */
            agent_trace_id?: string | null;
            /** Tool Name */
            tool_name: string;
            /** System */
            system?: string | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /** Args Hash */
            args_hash?: string | null;
            /** Read Only */
            read_only?: boolean | null;
            /** Status */
            status?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Result Ref */
            result_ref?: {
                [key: string]: unknown;
            } | null;
            /** Redactions */
            redactions?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    slack_events_slack_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    slack_commands_slack_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    slack_interactions_slack_interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    slack_oauth_callback_slack_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_detail_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_incidents__incident_id__summary_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facts_api_v1_incidents__incident_id__facts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: {
                system?: string | null;
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hypotheses_api_v1_incidents__incident_id__hypotheses_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_incidents__incident_id__questions_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenQuestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_incidents__incident_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_action_items_api_v1_incidents__incident_id__action_items_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_timeline_api_v1_incidents__incident_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mitigations_api_v1_incidents__incident_id__mitigations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationOptionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comms_api_v1_incidents__incident_id__comms_get: {
        parameters: {
            query?: {
                audience?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommsDraftRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_postmortem_api_v1_incidents__incident_id__postmortem_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostmortemDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_incidents__incident_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_v1_incidents__incident_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_v1_incidents__incident_id__revisions_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                since?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_incident_api_v1_incidents__incident_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live incident events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}