/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is running and can serve requests.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: dependencies (DB + Redis) are reachable.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Events
         * @description Events API endpoint: URL handshake + normalized event intake.
         */
        post: operations["slack_events_slack_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Interactions
         * @description Interactivity endpoint: buttons and menus steer the incident
         */
        post: operations["slack_interactions_slack_interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slack Oauth Callback
         * @description Install flow: exchange ``code`` and persist a ``workspaces`` row.
         */
        get: operations["slack_oauth_callback_slack_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description List incidents, newest first.
         */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        /**
         * Create Incident
         * @description Open an incident.
         */
        post: operations["create_incident_api_v1_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Incident Detail
         * @description Overview: the incident, its current summary, and per-entity counts.
         */
        get: operations["get_incident_detail_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        /**
         * Erase
         * @description Delete an incident and everything cascading from it.
         */
        delete: operations["erase_api_v1_incidents__incident_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description The current (highest-version) summary for a scope.
         */
        get: operations["get_summary_api_v1_incidents__incident_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facts */
        get: operations["list_facts_api_v1_incidents__incident_id__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evidence
         * @description Evidence for an incident, filterable by source system and status.
         */
        get: operations["list_evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hypotheses
         * @description Hypotheses with their supporting/contradicting evidence resolved.
         *
         *     Evidence is attached via the polymorphic ``evidence_links`` table, so this
         *     resolves links in two queries rather than one per hypothesis.
         */
        get: operations["list_hypotheses_api_v1_incidents__incident_id__hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_v1_incidents__incident_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_v1_incidents__incident_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Action Items */
        get: operations["list_action_items_api_v1_incidents__incident_id__action_items_get"];
        put?: never;
        /** Create Action Item */
        post: operations["create_action_item_api_v1_incidents__incident_id__action_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Timeline
         * @description Timeline ordered by when things happened, not when we recorded them.
         */
        get: operations["list_timeline_api_v1_incidents__incident_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/mitigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mitigations */
        get: operations["list_mitigations_api_v1_incidents__incident_id__mitigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/postmortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Postmortem
         * @description The latest postmortem draft (drafts are versioned like summaries).
         */
        get: operations["get_postmortem_api_v1_incidents__incident_id__postmortem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Investigation runs, most recent first.
         */
        get: operations["list_runs_api_v1_incidents__incident_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description A run with its agent traces and each trace's tool calls.
         */
        get: operations["get_run_detail_api_v1_incidents__incident_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Triggers
         * @description Trigger decisions for an incident, newest first
         */
        get: operations["list_triggers_api_v1_incidents__incident_id__triggers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incident Approvals
         * @description Approval requests, newest first.
         */
        get: operations["list_incident_approvals_api_v1_incidents__incident_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Revisions
         * @description The memory journal for an incident, oldest first (it reads as history).
         */
        get: operations["list_revisions_api_v1_incidents__incident_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Incident Usage
         * @description Token spend for an incident, per run and per agent, against its budget.
         */
        get: operations["get_incident_usage_api_v1_incidents__incident_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Everything the product holds about this incident, as one JSON document.
         */
        get: operations["export_api_v1_incidents__incident_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Mode
         * @description Set the behavior mode: quiet | scribe | assist | active.
         */
        post: operations["set_mode_api_v1_incidents__incident_id__mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Status
         * @description Move the incident status: open | mitigating | monitoring | resolved | closed.
         */
        post: operations["set_status_api_v1_incidents__incident_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Investigate
         * @description Queue a manual, targeted, read-only run.
         */
        post: operations["investigate_api_v1_incidents__incident_id__investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Fact
         * @description Correct a fact's wording, or mark it stale/rejected.
         */
        patch: operations["patch_fact_api_v1_incidents__incident_id__facts__fact_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/hypotheses/{hypothesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Hypothesis
         * @description Confirm or reject a hypothesis.
         */
        patch: operations["patch_hypothesis_api_v1_incidents__incident_id__hypotheses__hypothesis_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Evidence
         * @description Mark evidence stale — the only mutation an observation allows.
         */
        patch: operations["patch_evidence_api_v1_incidents__incident_id__evidence__evidence_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Question
         * @description Assign an owner, record an answer, or close a question.
         */
        patch: operations["patch_question_api_v1_incidents__incident_id__questions__question_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/action-items/{action_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Action Item */
        patch: operations["patch_action_item_api_v1_incidents__incident_id__action_items__action_item_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Approve or reject a gated recommendation
         */
        post: operations["decide_api_v1_incidents__incident_id__approvals__approval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Correction
         * @description Record a human correction; Scribe reconciles what it invalidates.
         */
        post: operations["submit_correction_api_v1_incidents__incident_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/postmortem/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Postmortem
         * @description Generate (or regenerate) the postmortem draft from current memory.
         */
        post: operations["generate_postmortem_api_v1_incidents__incident_id__postmortem_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Incident
         * @description Subscribe to an incident's live event feed.
         */
        get: operations["stream_incident_api_v1_incidents__incident_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemCreate */
        ActionItemCreate: {
            /** Description */
            description: string;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** ActionItemPatch */
        ActionItemPatch: {
            /** Status */
            status?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
        };
        /** ActionItemRead */
        ActionItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Description */
            description?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /**
         * AgentTokenUsage
         * @description One agent's share of an incident's tokens.
         */
        AgentTokenUsage: {
            /** Agent Name */
            agent_name: string;
            /** Calls */
            calls: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** AgentTraceRead */
        AgentTraceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Agent Name */
            agent_name: string;
            /** Seq */
            seq?: number | null;
            /** Status */
            status?: string | null;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Reasoning Summary */
            reasoning_summary?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Tokens */
            tokens?: {
                [key: string]: unknown;
            } | null;
            /** Model Name */
            model_name?: string | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRead"][];
        };
        /** ApprovalDecision */
        ApprovalDecision: {
            /** Decision */
            decision: string;
            /** Note */
            note?: string | null;
        };
        /** ApprovalRead */
        ApprovalRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Subject Type */
            subject_type?: string | null;
            /** Subject Id */
            subject_id?: string | null;
            /** Requested By */
            requested_by?: string | null;
            /** Requested At */
            requested_at?: string | null;
            /** Status */
            status: string;
            /** Decided By */
            decided_by?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorrectionCreate */
        CorrectionCreate: {
            /** Correction Text */
            correction_text: string;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
        };
        /**
         * CorrectionResult
         * @description What the correction recorded, and what it invalidated.
         */
        CorrectionResult: {
            fact: components["schemas"]["FactRead"];
            /** Invalidated */
            invalidated?: {
                [key: string]: string;
            }[];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** DecisionRead */
        DecisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Rationale */
            rationale?: string | null;
        };
        /**
         * ErasureReceiptRead
         * @description Proof of what a deletion removed.
         */
        ErasureReceiptRead: {
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Tombstone Id
             * Format: uuid
             */
            tombstone_id: string;
            /** Row Counts */
            row_counts?: {
                [key: string]: number;
            };
            /** Export Ref */
            export_ref?: string | null;
        };
        /**
         * ErasureRequest
         * @description ``DELETE /incidents/{id}`` body — deletion needs a stated reason.
         */
        ErasureRequest: {
            /** Detail */
            detail: string;
            /**
             * Reason
             * @default request
             */
            reason: string;
        };
        /**
         * EvidencePatch
         * @description Evidence accepts exactly one edit: marking it stale.
         */
        EvidencePatch: {
            /** Status */
            status: string;
        };
        /** EvidenceRead */
        EvidenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** System */
            system?: string | null;
            /** Query */
            query?: string | null;
            /** Result Ref */
            result_ref?: {
                [key: string]: unknown;
            } | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Staleness At */
            staleness_at?: string | null;
        };
        /** FactPatch */
        FactPatch: {
            /** Statement */
            statement?: string | null;
            /** Status */
            status?: string | null;
        };
        /** FactRead */
        FactRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HypothesisPatch */
        HypothesisPatch: {
            /** Status */
            status?: string | null;
            /** Rank */
            rank?: number | null;
        };
        /** HypothesisRead */
        HypothesisRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement?: string | null;
            /** Rank */
            rank?: number | null;
            /** Likelihood */
            likelihood?: number | null;
            /** Supporting Evidence */
            supporting_evidence?: components["schemas"]["EvidenceRead"][];
            /** Contradicting Evidence */
            contradicting_evidence?: components["schemas"]["EvidenceRead"][];
        };
        /** IncidentCreate */
        IncidentCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Channel Id */
            channel_id?: string | null;
            /** Alert Payload */
            alert_payload?: {
                [key: string]: unknown;
            } | null;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * IncidentDetail
         * @description Overview payload: the incident, its current summary, and counts.
         */
        IncidentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Slack Channel Id */
            slack_channel_id?: string | null;
            /** Slack Channel Name */
            slack_channel_name?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity?: string | null;
            /** Mode */
            mode: string;
            /** Started At */
            started_at?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Mitigated At */
            mitigated_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            summary?: components["schemas"]["SummaryRead"] | null;
            counts: components["schemas"]["IncidentSummaryCounts"];
        };
        /** IncidentRead */
        IncidentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Slack Channel Id */
            slack_channel_id?: string | null;
            /** Slack Channel Name */
            slack_channel_name?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity?: string | null;
            /** Mode */
            mode: string;
            /** Started At */
            started_at?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Mitigated At */
            mitigated_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IncidentSummaryCounts
         * @description Per-entity counts shown on the overview header.
         */
        IncidentSummaryCounts: {
            /**
             * Facts
             * @default 0
             */
            facts: number;
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /**
             * Hypotheses
             * @default 0
             */
            hypotheses: number;
            /**
             * Open Questions
             * @default 0
             */
            open_questions: number;
            /**
             * Decisions
             * @default 0
             */
            decisions: number;
            /**
             * Action Items
             * @default 0
             */
            action_items: number;
            /**
             * Timeline Entries
             * @default 0
             */
            timeline_entries: number;
            /**
             * Mitigation Options
             * @default 0
             */
            mitigation_options: number;
        };
        /**
         * IncidentUsage
         * @description Token spend for an incident against its budget
         */
        IncidentUsage: {
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Total */
            total: number;
            /** Runs */
            runs: number;
            /** Budget */
            budget: number;
            /** Remaining */
            remaining: number;
            /** Near Cap */
            near_cap: boolean;
            /** Exhausted */
            exhausted: boolean;
            /** By Run */
            by_run?: components["schemas"]["RunTokenUsage"][];
            /** By Agent */
            by_agent?: components["schemas"]["AgentTokenUsage"][];
        };
        /** InvestigateRequest */
        InvestigateRequest: {
            /** Target */
            target?: string | null;
            /** Since */
            since?: string | null;
            /** Focus */
            focus?: string | null;
        };
        /** MitigationOptionRead */
        MitigationOptionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Risk */
            risk?: string | null;
            /** Reversibility */
            reversibility?: string | null;
            /** Expected Benefit */
            expected_benefit?: string | null;
            /** Approval Required */
            approval_required?: boolean | null;
        };
        /** ModeUpdate */
        ModeUpdate: {
            /** Mode */
            mode: string;
        };
        /** OpenQuestionRead */
        OpenQuestionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Question */
            question?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Answer */
            answer?: string | null;
        };
        /** PostmortemDraftRead */
        PostmortemDraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Sections */
            sections?: {
                [key: string]: unknown;
            } | null;
            /** Follow Ups */
            follow_ups?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Version */
            version: number;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionPatch */
        QuestionPatch: {
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Status */
            status?: string | null;
            /** Answer */
            answer?: string | null;
        };
        /** RevisionRead */
        RevisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Op */
            op: string;
            /** Before */
            before?: {
                [key: string]: unknown;
            } | null;
            /** After */
            after?: {
                [key: string]: unknown;
            } | null;
            /** Diff */
            diff?: {
                [key: string]: unknown;
            } | null;
            /** Actor */
            actor?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Reason */
            reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunAccepted
         * @description A manual run was queued (it executes on the worker, not in-request).
         */
        RunAccepted: {
            /**
             * Status
             * @default queued
             */
            status: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Target */
            target?: string | null;
            /** Focus */
            focus?: string | null;
        };
        /**
         * RunDetail
         * @description A run plus its agent traces and the tool calls beneath them.
         */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Run Type */
            run_type: string;
            /** Trigger */
            trigger?: {
                [key: string]: unknown;
            } | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Token In */
            token_in?: number | null;
            /** Token Out */
            token_out?: number | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Limitations */
            limitations?: string[] | null;
            /** Summary */
            summary?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Agent Traces */
            agent_traces?: components["schemas"]["AgentTraceRead"][];
        };
        /** RunRead */
        RunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Run Type */
            run_type: string;
            /** Trigger */
            trigger?: {
                [key: string]: unknown;
            } | null;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Token In */
            token_in?: number | null;
            /** Token Out */
            token_out?: number | null;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Limitations */
            limitations?: string[] | null;
            /** Summary */
            summary?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunTokenUsage
         * @description Per-run usage — the row the run detail shows.
         */
        RunTokenUsage: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Type */
            run_type?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** StatusUpdate */
        StatusUpdate: {
            /** Status */
            status: string;
        };
        /** SummaryRead */
        SummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Scope */
            scope: string;
            /** Body */
            body?: string | null;
            /** Version */
            version: number;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TimelineEntryRead */
        TimelineEntryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Kind */
            kind?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by?: string | null;
            /** Status */
            status?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Entry Type */
            entry_type?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ToolCallRead */
        ToolCallRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Run Id */
            run_id?: string | null;
            /** Agent Trace Id */
            agent_trace_id?: string | null;
            /** Tool Name */
            tool_name: string;
            /** System */
            system?: string | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /** Args Hash */
            args_hash?: string | null;
            /** Read Only */
            read_only?: boolean | null;
            /** Status */
            status?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Result Ref */
            result_ref?: {
                [key: string]: unknown;
            } | null;
            /** Redactions */
            redactions?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TriggerRead
         * @description One trigger decision, with the reasons that produced it.
         */
        TriggerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Message Id */
            message_id?: string | null;
            /** Decision */
            decision?: string | null;
            /** Score */
            score?: number | null;
            /** Reasons */
            reasons?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    slack_events_slack_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    slack_interactions_slack_interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    slack_oauth_callback_slack_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_api_v1_incidents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_detail_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_api_v1_incidents__incident_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureReceiptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_incidents__incident_id__summary_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facts_api_v1_incidents__incident_id__facts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: {
                system?: string | null;
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hypotheses_api_v1_incidents__incident_id__hypotheses_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_incidents__incident_id__questions_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenQuestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_incidents__incident_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_action_items_api_v1_incidents__incident_id__action_items_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_action_item_api_v1_incidents__incident_id__action_items_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_timeline_api_v1_incidents__incident_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mitigations_api_v1_incidents__incident_id__mitigations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationOptionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_postmortem_api_v1_incidents__incident_id__postmortem_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostmortemDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_incidents__incident_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_v1_incidents__incident_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_triggers_api_v1_incidents__incident_id__triggers_get: {
        parameters: {
            query?: {
                decision?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incident_approvals_api_v1_incidents__incident_id__approvals_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_v1_incidents__incident_id__revisions_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                since?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_usage_api_v1_incidents__incident_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentUsage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_incidents__incident_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mode_api_v1_incidents__incident_id__mode_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_api_v1_incidents__incident_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_api_v1_incidents__incident_id__investigate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_fact_api_v1_incidents__incident_id__facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                fact_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_hypothesis_api_v1_incidents__incident_id__hypotheses__hypothesis_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                hypothesis_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HypothesisPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_evidence_api_v1_incidents__incident_id__evidence__evidence_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                evidence_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidencePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_question_api_v1_incidents__incident_id__questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                question_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenQuestionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_action_item_api_v1_incidents__incident_id__action_items__action_item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                action_item_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_incidents__incident_id__approvals__approval_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                approval_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_correction_api_v1_incidents__incident_id__corrections_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_postmortem_api_v1_incidents__incident_id__postmortem_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Flare-Actor"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostmortemDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_incident_api_v1_incidents__incident_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live incident events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
